version: '3'

services:
    php:
        build:
            context: .
            target: production
        restart: always
        networks:
            - default
        volumes:
            - ./symfony:/var/www/html

    http:
        build:
            context: .
            target: nginx
        ports:
            - 127.0.0.3:80:80
        restart: always
        volumes:
            - ./symfony:/var/www/html
        depends_on:
            - php
